routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/

$router->post('subscribe', 'SubscribeController@store');
$router->get('/', 'PageController@home');

app/Models/Meta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Meta extends Model
{
    protected $table = 'meta';

    protected $fillable = [
        'label',
        'qty',
        'type',
    ];
}

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    protected $table = 'notifications';

    protected $fillable = [
        'recipient',
        'type',
        'data',
        'status',
    ];
}

app/Models/Patient.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    protected $table = 'patients';

    protected $fillable = [
        'terkonfirmasi',
        'perawatan',
        'sembuh',
        'meninggal',
    ];

    public function getLastUpdatedAttribute()
    {
        // not sure yet, it seems lumen has some timezone issues?
        return Carbon::createFromFormat('Y-m-d H:i:s', $this->getAttribute('updated_at'))->addHours(8)->format('d/n/Y H:i');
    }
}

app/Models/Subscriber.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subscriber extends Model
{
    protected $table = 'subscribers';

    protected $fillable = [
        'contact',
        'type',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Database\Eloquent\Model;
use Laravel\Lumen\Auth\Authorizable;

class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Laravel\Lumen\Routing\Controller as BaseController;

class Controller extends BaseController
{
    //
}

app/Http/Controllers/ExampleController.php
<?php

namespace App\Http\Controllers;

class ExampleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    //
}

app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use App\Modules\DataViewer;

class PageController extends Controller
{
    public function home()
    {
        return view('home', [
            'patient' => (new DataViewer())->getPatients(),
        ]);
    }
}

app/Http/Controllers/SubscribeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Modules\SubscriberRepository;

class SubscribeController extends Controller
{
    public function store(Request $request)
    {
        $this->validate($request, [
            'contact' => 'required|email',
        ], [
            'required' => 'Form email harus diisi',
            'email' => 'Form email harus diisi email valid',
        ]);

        (new SubscriberRepository())->add($request->all());

        return response('Ok, email tersimpan');
    }
}

resources/views/home.blade.php
@extends("layouts.app")

@section("content")
    <div class="stats">
        <div class="case --terkonfirmasi">
            <h2>{{ $patient->terkonfirmasi }}</h2>
            <span>Terkonfirmasi</span>
        </div>
        <div class="case --perawatan">
            <h2>{{ $patient->perawatan }}</h2>
            <span>Dalam Perawatan</span>
        </div>
        <div class="case --sembuh">
            <h2>{{ $patient->sembuh }}</h2>
            <span>Sembuh</span>
        </div>
        <div class="case --meninggal">
            <h2>{{ $patient->meninggal }}</h2>
            <span>Meninggal</span>
        </div>
    </div>

    <div class="subscribe">
        <p>Dapatkan pembaharuan setiap ada perubahan data / jumlah pasien di inbox email anda</p>
        <input type="email" name="contact" required placeholder="Ketik email anda disini">
        <input type="submit" value="subscribe">
    </div>

    <div class="disclaimer">
        <strong>Catatan</strong>
        <ul>
            <li>Terakhir diperbarui <strong>{{ $patient->last_updated }}</strong></li>
            <li>Data diambil dari kawalcovid19.id</li>
            <li>kawalcovid19.id menggunakan data dari penginputan kontributor yang bisa jadi tidak menggambarkan kejadian real time sebenarnya</li>
            <li>Data lebih lengkap bisa dilihat disini <a href="https://kcov.id/daftarpositif" target="_blank">https://kcov.id/daftarpositif</a>
        </ul>
    </div>
@endsection

@section("js")
<script>
    $("input[type='submit']").on("click", function() {
        $.post('subscribe', {"contact": $("input[type='email']").val()})
            .fail(function(response) {
                alert(response.responseJSON.contact[0]);
                $("input[type='email']").focus();
            })
            .then(function(response) {
                alert(response);
            });
    });
</script>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta property="og:url" content="https://covid.fullstack.id" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Waspada Covid-19!" />
    <meta property="og:description" content="Monitoring jumlah kasus Covid-19 terbaru" />
    <meta property="og:image" content="preview.png" />
    <meta name="twitter:title" content="Waspada Covid-19!">
    <meta name="twitter:description" content="Monitoring jumlah kasus Covid-19 terbaru">
    <meta name="twitter:image" content="preview.png">
    <meta name="twitter:card" content="summary_large_image">

    <title>Waspada Covid-19</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Waspada Covid-19</h1>
        <p>Monitoring jumlah korban Covid-19 di Indonesia</p>
        <p>Sumber data: <a href="https://kawalcovid19.id" target="_blank">kawalcovid19.id</a></p>
    </header>

    <section id="content">
        @yield("content")
    </section>

    <footer>
        Just another project by <a href="http://yogasukma.web.id" target="_blank">Yoga Sukma</a> - 
        (<a href="https://gitlab.com/yogasukma/covid19" target="_blank">source code</a>)
    </footer>

    <script src="jquery.js"></script>
    @yield("js")
</body>
</html>